export const buttonsData = [
  { label: "Action", slug: "action" },
  { label: "Indie", slug: "indie" },
  { label: "Adventure", slug: "adventure" },
  { label: "RPG", slug: "role-playing-games-rpg" },
  { label: "Strategy", slug: "strategy" },
  { label: "Shooter", slug: "shooter" },
  { label: "Casual", slug: "casual" },
  { label: "Simulation", slug: "simulation" },
  { label: "Puzzle", slug: "puzzle" },
  { label: "Arcade", slug: "arcade" },
  { label: "Platformer", slug: "platformer" },
  { label: "Racing", slug: "racing" },
  { label: "Massively Multiplayer", slug: "massively-multiplayer" },
  { label: "Sports", slug: "sports" },
  { label: "Fighting", slug: "fighting" },
  { label: "Family", slug: "family" },
  { label: "Board Games", slug: "board-games" },
  { label: "Educational", slug: "educational" },
  { label: "Card", slug: "card" },
];
