export const checkboxData = [
  { label: "All genres", parameter: "" },
  { label: "Action", parameter: "&genres=action" },
  { label: "Indie", parameter: "&genres=indie" },
  { label: "Adventure", parameter: "&genres=adventure" },
  { label: "RPG", parameter: "&genres=role-playing-games-rpg" },
  { label: "Strategy", parameter: "&genres=strategy" },
  { label: "Shooter", parameter: "&genres=shooter" },
  { label: "Casual", parameter: "&genres=casual" },
  { label: "Simulation", parameter: "&genres=simulation" },
  { label: "Puzzle", parameter: "&genres=puzzle" },
  { label: "Arcade", parameter: "&genres=arcade" },
  { label: "Platformer", parameter: "&genres=platformer" },
  { label: "Racing", parameter: "&genres=racing" },
  {
    label: "Massively Multiplayer",
    parameter: "&genres=massively-multiplayer",
  },
  { label: "Sports", parameter: "&genres=sports" },
  { label: "Fighting", parameter: "&genres=fighting" },
  { label: "Family", parameter: "&genres=family" },
  { label: "Board Games", parameter: "&genres=board-games" },
  { label: "Educational", parameter: "&genres=educational" },
  { label: "Card", parameter: "&genres=card" },
];
